### ISSUE TITLE
Obtain ACCESS TOKEN does not work

### ISSUE THREAD

**Issue by ale-jin** [simplefx-ltd/simplefx-api#1]
The procedure "Obtain ACCESS TOKEN" dos not work, when you follow the steps in the swagger interface the response is a 200 code, but you get the start page of simpleFX, not the access token.

**Comment by kdsull** [comment]
Man, this is worrying... Does anyone maintain this code, at all ?! Whenever I try Authentification, I always get {
  "code": 1501,
  "message": "AUTHENTICATION_INVALID_CREDENTIALS",
  "webRequestId": "104-dd3a359b-d96d-4d8d-ae98-ea8d25236f42"
}
.
Yes, I've tried with MANY confirmed secret keys... 
It's good to see that simplefx provide this nice REST API, but wish it's properly working.

**Comment by sfx-ltd** [comment]
Let me check it

**Comment by sfx-ltd** [comment]
Hmm I have just used swagger for 
sending POST to https://rest.simplefx.com/api/v3/auth/key
with body 
{
  "clientId": "989c4d44410d40aa9ffe04c1401a9fe8",
  "clientSecret": "*****"
}

And received token as

{
  "data": {
    "token": "*********"
  },
  "code": 200,
  "message": "OK",
  "webRequestId": "204-7a255687-609f-4c88-988b-18b7e49db720"
}

You sure your api key is confirmed?

**Comment by sfx-ltd** [comment]
@ale-jin
On top of swagger page above the AUTHENTICATION, there is ability to select server.
Be sure it is "https://rest.simplefx.com" rather than "/"
I will check if I can remove misleading "/" server.

**Comment by sfx-ltd** [comment]
@kdsull I do not see your webRequestId in logs, can you show API_KEY_ID (clientId) - but mind not to share secret.

**Comment by kdsull** [comment]
Many thanks for your support. I currently am using Bitmex and Deribit APIs with Python, so I really would like to sort this out. I'm trying two IDs, 'sfHamjii' and 'sf2Hamjii', and the curl command looks like :

curl -X POST "https://rest.simplefx.com/api/v3/auth/key" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"clientId\":\"sf2Hamjii\",\"clientSecret\":\"********************\"}"

and the response is, always ! :

{
  "code": 1501,
  "message": "AUTHENTICATION_INVALID_CREDENTIALS",
  "webRequestId": "105-7281e850-e4bd-45d0-b105-1643cf98cfa3"
}

I see that "https://rest.simplefx.com" server is selected, and my two IDs are confirmed via e-mail. I know that I can do many interesting things when I get passed this Auth, but can't get this working now !!

**Comment by sfx-ltd** [comment]
@kdsull you are pasting description you named the api key. You need to paste api key id, your is like 'a7e*****************************'

**Comment by sfx-ltd** [comment]
I have removed misleading "/" server and added note about how api_key_id and api_key_secret looks like.

**Comment by kdsull** [comment]
Ou, shoooot.... Now I got it ! 
Many many thanks for your help. 
I definately was confused, coz I've never seen such looong keys, if not secrets !!

Thanks again, and cheers !
