### ISSUE TITLE
Unable to generate client

### ISSUE THREAD

**Issue by Marfusios** [simplefx-ltd/simplefx-api#2]
Hello, 

I was really struggling today with generating C#/.NET client for REST API. Tried NSwag studio, OpenAPI generator, nothing worked, always got a lot of errors. 
Then I figured out that provided [json file](https://simplefx.com/docs/api/oas3-3.0.json) is **not even valid** json!  

Please fix it, I had to modify json manually and then was able to generate client: https://github.com/Marfusios/simplefx-client-rest 

I've not tried trade API, just getting account info/balance and instruments. 
So not sure if the client covers full API.

**Comment by sfx-ltd** [comment]
Dear Mariusz,

Thank you for your message and sorry for the inconvenience, our IT Team is working on it. We will let you know when the fix will be released.

Best Regards
SimpleFX Support Team

**Comment by sfx-ltd** [comment]
Dear Mariusz,

The issue was solved. In case of any further comments or questions please contact us at the email address: support@simplefx.com

Best Regards
SimpleFX Support Team

**Comment by Marfusios** [comment]
@simplefx-ltd ,

unfortunately still invalid json, see: 

![image](https://user-images.githubusercontent.com/3494837/71981306-6f8cd980-3222-11ea-9bcc-0f71db5c2c6e.png)

You can check it here: https://jsonformatter.curiousconcept.com

**Comment by sfx-ltd** [comment]
Dear Mariusz,

We have checked https://simplefx.com/docs/api/oas3-3.0.json on https://jsonformatter.curiousconcept.com/ and JSON is valid (see attached screen), 

Please clear your browser data or use incognito and then try again. 

![image](https://user-images.githubusercontent.com/16382061/72099211-70a43080-3320-11ea-8f2d-a8e1036d2bf8.png)

Best Regards
SimpleFX Support Team

**Comment by Marfusios** [comment]
Perfect, now it works, thanks.
