### ISSUE TITLE
Is the url for quote API up to date?

### ISSUE THREAD

**Issue by FlyCapital** [simplefx-ltd/simplefx-api#7]
I try to connect to quote API to get market quotes as instructed in the [API doc](https://github.com/simplefx-ltd/simplefx-api) in the link below (section “Quotes and Prices”), but I have trouble connecting to it. Can I confirm "https://webquotes-v3.simplefx.com/signalr/“ is the right url for it? Is it actively supported?

**Comment by sfx-ltd** [comment]
Sorry for late answer @FlyCapital
Yes, this is the right URL. Please note that this is SignalR 2.x API and not SignalR Core. As of today it's marked as deprecated. Please use [raw WebSocket API](https://github.com/simplefx-ltd/simplefx-api/tree/docs-update?tab=readme-ov-file#simplefx-websocket-api-documentation) instead.
